"""make documents uploaded_by nullable until auth exists

Revision ID: ef27b14ed327
Revises: 162bae78997f
Create Date: 2026-07-28 13:00:47.654815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef27b14ed327'
down_revision: Union[str, None] = '162bae78997f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
